github.com:
    users:
        codewithkin:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: codewithkin
